In [1]:
import pandas as pd
import numpy as np

from dsgd.DSClassifierMultiQ import DSClassifierMultiQ

from sklearn.metrics import accuracy_score, confusion_matrix, f1_score


In [2]:
df = pd.read_csv("https://huggingface.co/datasets/furrutiav/sac_nllf/raw/main/train.csv")
df = df.drop(columns=['index'])
print("Dataframe shape: ", df.shape)
df.head()
test = pd.read_csv("https://huggingface.co/datasets/furrutiav/sac_nllf/raw/main/val.csv")
test = test.drop(columns=['index'])
print("Dataframe shape: ", test.shape)

Dataframe shape:  (1400, 27)
Dataframe shape:  (200, 27)


In [3]:
y = df['label']
X = df.drop(columns=['label'])
y = y.to_numpy()
X = X.to_numpy()    
y_test = test['label']
X_test = test.drop(columns=['label'])
X_test = X_test.to_numpy()
y_test = y_test.to_numpy()

In [4]:
DSCs = {}
time = {}
accuracys = {}
learning_rates = [0.1, 0.01]
batch_sizes = [2000, 3000, 4000]
min_dl = [1e-7, 1e-6, 1e-5,]
num_rules = [3, 5, 7,]
for lr in learning_rates:
    for bs in batch_sizes:
        for mdl in min_dl:
            for nr in num_rules:
                DSC = DSClassifierMultiQ(2, min_iter=20, max_iter=1000, debug_mode=True, lr=lr, batch_size=bs,
                                lossfn="MSE", num_workers=1, min_dloss=mdl, precompute_rules=True)
                print(f"Training DSC with lr={lr}, bs={bs}, mdl={mdl}, nr={nr}")
                losses, epoch, dt = DSC.fit(X, y, add_single_rules=True,
                            single_rules_breaks=nr, add_mult_rules=False,
                                column_names=df.columns[:-1], print_every_epochs=1, print_final_model=False)
                y_pred = DSC.predict(X_test)
                acc = accuracy_score(y_test, y_pred)
                f1_micro = f1_score(y_test, y_pred, average='micro')
                f1_macro = f1_score(y_test, y_pred, average='macro')
                print(f"Accuracy: {acc}")
                print(f"F1 Micro: {f1_micro}")
                print(f"F1 Macro: {f1_macro}")
                print(confusion_matrix(y_test, y_pred))

Training DSC with lr=0.1, bs=2000, mdl=1e-07, nr=3
Optimization started
Processing epoch	26	0.2030	
Training time: 58.81s, epochs: 26

Least training loss reached: 0.204
Accuracy: 0.69
F1 Micro: 0.69
F1 Macro: 0.6892230576441103
[[74 38]
 [24 64]]
Training DSC with lr=0.1, bs=2000, mdl=1e-07, nr=5
Optimization started
Processing epoch	23	0.1958	
Training time: 51.98s, epochs: 23

Least training loss reached: 0.198
Accuracy: 0.685
F1 Micro: 0.685
F1 Macro: 0.6827075621364358
[[77 35]
 [28 60]]
Training DSC with lr=0.1, bs=2000, mdl=1e-07, nr=7
Optimization started
Processing epoch	24	0.1940	
Training time: 54.51s, epochs: 24

Least training loss reached: 0.194
Accuracy: 0.69
F1 Micro: 0.69
F1 Macro: 0.6895032051282051
[[73 39]
 [23 65]]
Training DSC with lr=0.1, bs=2000, mdl=1e-06, nr=3
Optimization started
Processing epoch	22	0.2166	
Training time: 50.36s, epochs: 22

Least training loss reached: 0.222
Accuracy: 0.635
F1 Micro: 0.635
F1 Macro: 0.6260150106303952
[[79 33]
 [40 48]]
Trai

KeyboardInterrupt: 